### ISSUE TITLE
Soulbound/scam trade thing

### ISSUE THREAD

**Issue by DaLegend27** [LoESoft-Games/LOE-V6#12]
Weapon slot: A soulbound sword
slot 1: t0 sword
start a trade
press 1
trade t0 sword
they will get the weapon u had equiped and the t0 s word will be equiped

**Comment by DaLegend27** [comment]
nvm, the trade breaks if u do it

**Comment by Devwarlt** [comment]
This issue no longer exist in build 1.6.6, since it contains internal boolean variable whose disable player to do use / drop / swap action while trading with other player.
