### ISSUE TITLE
sprite glitch thing?

### ISSUE THREAD

**Issue by FartSmart** [LoESoft-Games/LOE-V6#14]
im not sure if its meant to look like that as a joke or not but here (btw the item is the doom spoon)

![image](https://user-images.githubusercontent.com/36826323/36926073-2a270e2c-1e76-11e8-9f63-f4beb157454c.png)

**Comment by Devwarlt** [comment]
Certain stuffs will not be accessed by players, therefore exclusive for game staff role.
