### ISSUE TITLE
Quiver bug

### ISSUE THREAD

**Issue by davyk1** [LoESoft-Games/LOE-V6#15]
![screenshot_1372](https://user-images.githubusercontent.com/31628094/36937206-2492a0a2-1ea3-11e8-88c0-1199ecb76939.png)
Quivers don't shoot unless you are shooting your bow and when they do, they shoot off-centre.

**Comment by Devwarlt** [comment]
Actually all abilities are working, but only abilities whose throw projectiles aren't displaying them, this issue will be patched asap.

**Comment by Devwarlt** [comment]
Issue solved, added new exception in player shoot handler (server side).

**Comment by Devwarlt** [comment]
Duplicated issue #8
