### ISSUE TITLE
More issues pt2

### ISSUE THREAD

**Issue by Filisha223** [LoESoft-Games/LOE-V6#4]
-sprite god produce sprite child too much
-a lot of behaviors need fixing
-enemys take too long to die which is annoying.

**Comment by FartSmart** [comment]
you a fat frog

**Comment by Devwarlt** [comment]
- Sprite God minions spawn less now, also Sprite God only reproduce them if there is none in range of 35 sqrs and max was set to 5;
- Enemy death is not causing any trouble.
