### ISSUE TITLE
some ability bugs

### ISSUE THREAD

**Issue by FartSmart** [LoESoft-Games/LOE-V6#8]
knights,ninjas,archers abilitys dont  work and assasins ability spawns one of those white pentract things when ever you use the ability. all other class abilitys work from what i tested
![image](https://user-images.githubusercontent.com/36826323/36791315-c37d15ca-1c97-11e8-864b-12f8e0812241.png)

**Comment by Devwarlt** [comment]
Not all abilities were added, incoming for new versions.
